apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
  namespace: api
data:
  index.html: |
    <html>
    <head><title>App1</title></head>
    <body><h1>Welcome to App1</h1></body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
  namespace: api
data:
  index.html: |
    <html>
    <head><title>App2</title></head>
    <body><h1>Welcome to App2</h1></body>
    </html>
