apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
  namespace: api
data:
  app1.conf: |
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html/app1;
            index index.html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-config
  namespace: api
data:
  app2.conf: |
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html/app2;
            index index.html;
        }
    }
